### ISSUE TITLE
Criar Tela de visualização do posto

### ISSUE THREAD

**Issue by adryanoalf** [adryanoalf/RefillMe#4]

**Comment by caioromao** [comment]
Não esquecer da estrutura da visualização do posto, que será composta de:

- Botões "Voltar" e "Avaliar Posto"
- Imagem do posto
- Endereço do posto
- Preço dos combustíveis neste posto
- Classificação do posto de acordo com os usuários (de 1 até 5 estrelas)

**Comment by caioromao** [comment]
Referência:
https://docs.google.com/presentation/d/1Vqn273uJhfTRwRgdIWa2PbxN2MRM31AvWiK8peoO6-k/edit#slide=id.g22895848fd_1_49

Slide 11

**Comment by caioromao** [comment]
Não esquecer de adicionar a informação:

"Data da última atualização", para que o usuário saiba qual foi o dia em que os preços foram atualizados pela última vez pelo administrador do posto.

**Comment by caioromao** [comment]
Implementação realizada. Tudo ok.
